# Generated by Django 2.0.5 on 2018-05-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_At',
            new_name='update_at',
        ),
    ]
